//Number is greater than 7...
NUM > 7

//number is less than -3...
NUM <-3

//Number is greater than 10....
NUM > 10

//Number is 0....
num == 0

//Number is non-zero without using Not Equal to...
Num > 0

//Number is positive...
Num >= 0

//Number is negative....
Num < 0

//Number is Divisible by 3...
Num%3==0

//Number is Divisible by 7...
Num%7==0

//Number is Divisible by 6...
Num%6==0

//Number is Divisible by 6 without directly Dividing by 6....
Num%2==0 && Num%3==0

//Number is greater than 10 and less than 20....
Num>10 && Num<20

//Number is more than 50 and less than 150...
Num>50 && Num<150

//Number is larger than 1000 and smaller than 1900...
Num>1000 && Num<1900

//Number is less than or equal with 10...
Num<=10

//Number can be 1, Number can be 2, number can be 3, number can be 5....
Num==1 || Num==2 || Num==3 || Num==5

//Number is even....
Num%2==0

//Number is odd....
Num%2!=0 || Num%2==1

//person is eligible to vote...
Num>18?"Eligible to vote":"Not eligible to vote"


//if the students is getting a score/marks 45 or less than 50 than 3rd division...
marks>45 && Marks<50 

//if the student is getting more than 50 and less than 60 than second division....
Num>50 && Num<60

//if the student is greater than 60 and less than 75 than First division....
Num>50 && Num<60

//if day number is 1 than it is 'monday'...
Day==1

//if day number is 7 than it is Sunday...
Day==7

//if option is one than the selection is pizza...
Option==1

//if option is two than selection is burger...
option==2

//Character is capital A...
char c='A';

//Character is small a...
char c='a';


//Character is capital M...
char c='M';


//Character is smaller y...
char c='y';


//Character is Upper case D...
char c='D';


//Character is capital D...
char c='D';


//Character is Smaller r...
char c='r';


//Character is Vowel...
char Vowel1='a' , Vowel2='e' , Vowel3='i' , Vowel4='o' , Vowel5='u', Vowel6='A' , Vowel7='E' , Vowel8='I' , Vowel9='O' , Vowel10='U' ;

//Character is uper case vowel...
char Vowel1='A', Vowel2='E', Vowel3='I', Vowel4='O', Vowel5='U';

//Character is lower case vowel...
char Vowel1='a' , Vowel2='e' , Vowel3='i' , Vowel4='o' , Vowel5='u';

//Character is constant...
char Vowel1!='a' , Vowel2!='e' , Vowel3!='i' , Vowel4!='o' , Vowel5!='u', Vowel6!='A' , Vowel7!='E' , Vowel8!='I' , Vowel9!='O' , Vowel10!='U';

//Character is upper case constant...
char const1='B', const2='C', const3='D', const4='F',const5='G', const6='H',const7='J', const8='K',const9='L', const10='M',const11='N', const12='P',const13='Q', const14='R',const15='S', const16='T',const17='V', const18='W',const19='X', const20='Y',const21='Z';

//Character is lower case constant...
char const1='b', const2='c', const3='d', const4='f',const5='g', const6='h',const7='j', const8='k',const9='l', const10='m',const11='n', const12='p',const13='q', const14='r',const15='s', const16='t',const17='v', const18='w',const19='x', const20='y',const21='z';

//Character is special character...
char Spcl='@', Spcl1='#', Spcl2='$';

//Character is Star...
char Star='*';

//Character is hash...
char Hash='#';

//Character is Space...
Char Space=' ';

//Character is Lower case character...
char Chr1='b', Chr2='c', Chr3='d', Chr4='f',Chr5='g', Chr6='h', Chr7='j', Chr8='k', Chr9='l', Chr10='m', Chr11='n', Chr12='p',Chr13='q', Chr14='r', Chr15='s', Chr16='t', Chr17='v', Chr18='w', Chr19='x', Chr20='y', Chr21='z', Chr22='a', Chr23='e', Chr24='i', Chr25='o', Chr26='u';

//Character is upper case constant...
char chr1='a', chr2='B', chr3='C', chr4='D', chr5='e', chr6='F',chr7='G', chr8='H', chr9='i', chr10='J', chr11='K', chr12='L', chr13='M', chr14='N',chr15='o', chr16='P', chr17='Q', chr18='R', chr19='S', chr20='T', chr21='u', chr22='V', chr23='W', chr24='X', chr25='Y', chr26='Z';

//Name is debasis…
String Name="DEBASIS";

//Password is 123…
Int Pswrd=123;
	
//EMAIL ID…
String EmailID="mrvihaan031@gmail.com";
	
//GIVE ME YOUR OTP…..
Int OTP=7562;

